### PR TITLE
add .tokenSet()

### PR DESCRIPTION
**Pull request by craigmulligan**
Connects #25 
adds `.tokenSet(<token>)`

Looks worse than it is, basically just offloaded token management to `axios` and removed a lot handlers we didn't need.

#29 should be merged first.

### CODE REVIEW

**Review by nopbyte — CHANGES_REQUESTED** [review]
Hi @craig-mulligan 
I think removing the then clause at the end will break components using the sdk because we are not returning the data but the whole request. When I tried this in my examples, I got: TypeError: Converting circular structure to JSON when I tried to print the result from the calls.

I would guess this happens because of the recusrive structure of requests. So, I think we still need to return just res.data

**Comment by craigmulligan** [comment]
Hmm, the only method I see returning the whole request is `agile.idm.user.delete` is that what broke it?

**Comment by nopbyte** [comment]
As far as I can see. You removed several lines doing this:
```
.then(res => (res.data))
.catch(errorHandler);
```
Doesn't this affect somehow? 
I know that you added something to the axios.interceptors.response, but I don't really know how axios handles this.

did you test the ui after the changes for example?

**Comment by craigmulligan** [comment]
Yea, but I added a global interceptor to modify the response - see here: https://github.com/Agile-IoT/agile-sdk/pull/30/files#diff-2b4ca49d4bb0a774c4d4c1672d7aa781R4

It's the same as doing it mainly just with less code repetition.

**Comment by nopbyte** [comment]
Hi @craig-mulligan,

Ok. the issue that I had while testing is in src/idm/authentication.js.

Specifically, I think the problem relates to  how we work around the issues that axios has to generate POST with application/x-www-form-urlencoded when interceptors are used. So we were generating a new instance according [to this discussion](https://github.com/mzabriskie/axios/issues/362).

This is currently not working after the change.

**Comment by craigmulligan** [comment]
@nopbyte, thanks for pointing that out. I missed updating the Authentication methods. I've checked all node examples in the `/idm` everything looks like it's working.

**Review by nopbyte — APPROVED** [review]
@craig-mulligan 
Thanks for the update in the examples, it is cleaner to update also the URLs in one site now.

**Pull request merged**
