### PR TITLE
Update license

### PR DESCRIPTION
**Pull request by craigmulligan**
Change-Type: patch

### CODE REVIEW

**Comment by craigmulligan** [comment]
Connects to #39

**Comment by phkrief** [comment]
@craig-mulligan , @geomic,
Based on (1) the description of this module and (2) the contributors which are not only Resin.io, I don't understand why you decided to set the license to Apache. In my understanding, the only code specifically developed by Resin.io and extending the ResinOS will be under the Apache license or dual license.
Do I miss something here?
Did you inform the other contributors like @nopbyte ?

Thanks

**Comment by craigmulligan** [comment]
@phkrief, I read the #39 where you said - `resin.io was planning to use only EPL or Apache license`? so I choose Apache, I wasn't at any of the licensing meetings, so @geomic please can you confirm which license to use here?

**Comment by phkrief** [comment]
@craig-mulligan , 
So, finally, this component is also part of ResinOS?
Did you talk with @geomic ?
Our final proposal was: any extension of ResinOS could/should stay in your current/default Resin.io repo with the Apache 2.0 license.
Anything else, specifically developed for AGILE should be under the EPL 2.0 license to be easily pushed as an initial contribution to the project. Wayne beaton would like to avoid to manage a secondary license in a separate project.

If you don't get the point,  as I already suggested, I will be more than happy to have a call with you to clarify it.
Thanks for your understanding

FYI  @cskiraly

**Comment by geomic** [comment]
@phkrief are you joining us in Brussels next week to briefly touch on this?

This isn't part of resinOS -- apologies as a couple pending items were closed as Craig was sorting out loose ends.

Either way, I still think wires are crossed still, with regards to licensing. I understood from the call that there was no issue at all with a dual license (EPL 2 and Apache 2), and agreement from Wayne that we could merely flag the AGILE repos here, and later AGAIL repos, as such (dual licensed).

We communicated a summary over email, with what essentially was discussed in the call:
* Dual licensing not an issue for AGILE/AGAIL components
* Stick to current arrangement for separate resin.io/resinOS components which may (and will) be consumed by AGILE/AGAIL code and repositories, but are in a different organisation so to speak, as long as they're open sourced (which is the case)

Let us know if this changes for some reason.

**Pull request closed without merging**
